#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_nombre_chance: #nom de la route
  path: /chance/nombre #url
  controller: App\Controller\ChanceController::nombre #chemin du controller + fonction