<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEG0BCxC\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEG0BCxC/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEG0BCxC.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEG0BCxC\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEG0BCxC\App_KernelDevDebugContainer([
    'container.build_hash' => 'EG0BCxC',
    'container.build_id' => 'de5b7f39',
    'container.build_time' => 1638955476,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEG0BCxC');
