<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVn5x1WB\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVn5x1WB/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVn5x1WB.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVn5x1WB\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVn5x1WB\App_KernelDevDebugContainer([
    'container.build_hash' => 'Vn5x1WB',
    'container.build_id' => '4e96928b',
    'container.build_time' => 1638777684,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVn5x1WB');
