<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJm4fzjm\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJm4fzjm/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJm4fzjm.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJm4fzjm\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJm4fzjm\App_KernelDevDebugContainer([
    'container.build_hash' => 'Jm4fzjm',
    'container.build_id' => '9ee957da',
    'container.build_time' => 1638884178,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJm4fzjm');
